name: check-quality
on:
  push:
    branches:
      - main
jobs:
  check-quality-cms:
    runs-on: self-hosted
    defaults:
      run:
        shell: bash
        working-directory: ./aww-cms
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 16
          cache: 'npm'
          cache-dependency-path: ./aww-cms/yarn.lock
      - name: Install dependencies
        run: |
          npm install
          npm run build
  check-quality-frontend:
    needs: check-quality-cms
    runs-on: self-hosted
    defaults:
      run:
        shell: bash
        working-directory: ./aww-frontend
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 16
          cache: 'npm'
          cache-dependency-path: ./aww-frontend/yarn.lock
      - name: Install Dependencies
        run: |
          npm install
          npm run build
      - name: Lint check
        run:  npm run lint